[package]
name = "message"
version = "0.1.0"
authors = ["richardyao <richardyao@tencent.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
thread-id = "3.3.0"
gettid = "0.1.1"